### ISSUE TITLE
Same value produced for consecutive fuzz calls.

### ISSUE THREAD

**Issue by chrisparnin** [johnnyrockett/rog#1]
Added the following code to the test suite and ran `mvn test`.

```java
    public void testString()
    {
        // Make it with an array of string paths to the .class files
        String[] sPaths = {".../target/classes"};
        ROG rog = new ROG(sPaths);

        for( int i =0; i<100; i++ )
        {
            String str = (String)rog.getInstance(String.class);
            System.out.println(str);
        }

    }
```

While random strings were produced, I noticed that they often were the same string being returned across multiple calls. I suspect this is due to sensitivity of random seeding to current time?

![image](https://user-images.githubusercontent.com/742934/54048111-cb23ac00-41a6-11e9-81e0-718991868f86.png)

**Comment by johnnyrockett** [comment]
The problem was that I was seeding my randomness with the current time in millis which wasn't atomic enough for rapid fire object creation. Replacing the millis with System.nanoTime() produces the following results with the same test:

<img width="303" alt="screen shot 2019-03-08 at 1 49 54 pm" src="https://user-images.githubusercontent.com/3711274/54049007-5736d300-41a9-11e9-84a4-5159373439b5.png">

I'll push this change out.

**Comment by johnnyrockett** [comment]
Small note: after some research, Java's Random object does good atomic randomness by default. New push will leave the logic up to this Random object.
